# Generated by Django 6.0.7 on 2026-08-05 09:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Идентификатор компании может содержать только латинские буквы, цифры, дефис и подчёркивание.', regex='^[A-Za-z0-9_-]+$')], verbose_name='ID компании в TitanRetail')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступ разрешён')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'доступ к компании',
                'verbose_name_plural': 'доступы к компаниям',
                'ordering': ('company_name', 'company_id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'company_id'), name='unique_user_company_access')],
            },
        ),
    ]
